### PR TITLE
Fourth lab

### PR DESCRIPTION
**Pull request by gorobot-nz**
Link - `https://gorobot-nz.github.io/calendarproj/project/index.html`

Now app has basic functionality(CRUD for main challenge types)
All challenges are saved in Firebase
Now i don't have any auth except simple username input
This is the structure of Firebase
screen
I will fix CalendarEvents in few days to display them weekly, but i need first review now

I have the following questions
What should I fix now? (The main problem that i see is chain of callbacks for component in render functions of class.)
Can this Firebase interaction be approved as part of fifth lab? 
I don't know how to formulate last question, but 4 will suit me for some minimum

### CODE REVIEW

**Comment by katetushkan** [comment]
The firebase part can be count as a part of the 5th lab
Screenshot 2022-03-22 at 16 25 45
something is not working here - I assume that's the part u mention in ur comment.
Screenshot 2022-03-22 at 16 26 36

I'm not able to register user, or it's happening but nothing is displayed.

Tell me pls, where do u have problem with callbacks?

**Comment by katetushkan** [comment]
Screenshot 2022-03-22 at 20 00 56
When I'm clicking "save" btn, no "day" variable coming here:
Screenshot 2022-03-22 at 20 01 32

**Comment by gorobot-nz** [comment]
> I'm not able to register user, or it's happening but nothing is displayed.
Yes
If it's necessary, I can probably make a window appear for a while with info

Before challenge creating you should click day 
Main question was about strongly related components

**Comment by gorobot-nz** [comment]
> > I'm not able to register user, or it's happening but nothing is displayed.
> 
> Yes If it's necessary, I can probably make a window appear for a while with info
> 
> Before challenge creating you should click day Main question was about strongly related components

**Comment by katetushkan** [comment]
>> Main question was about strongly related components

Can you give an example of the component that bothers you? Or a piece of code that you don't like.

**Comment by katetushkan** [comment]
Okay you components look like [custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) except that they are not)

I'd suggest you adopt the technique described in the article above in your code. It is a native convenient way to work with components.

One more good thing to have is a separation of concerns. Your components should only be responsible for data display and event handling. Work with Firebase, localStorage or other data sources should ideally not happen in them. I see that you put data in firebase in a form, which is okay. Not really good, but okay. Ideally form should send an event (onSubmit) to the container and container should handle the call to firebase.

Also, for picking day and user login. User should see that smth is happening. At least, close login pop-up after user is created, and add style to the picked day.

Good luck! U are doing good.)

**Comment by katetushkan** [comment]
do u want me to wait for ur changes for Custom elements? Or u want me to check it how it is now.

**Review by katetushkan — APPROVED** [review]
Okay, I'll give u a 10. but add close ur pop up after submitting user name or a task

That's what I'm talking about. After I press "set user", modal window should close.
Screenshot 2022-03-28 at 15 08 16

Or after I adding an event 
Screenshot 2022-03-28 at 15 09 44

Ur Firebase part is counted as a part of lab #5. In addition to it u can add Repository module^ for example.

I can let u start with the 6th work, and add ur modules in it. So u can skip 5th work and start working on the 6th lab.

**Comment by gorobot-nz** [comment]
Thank
The last question
Task of the 6th lab - rewrite project in JS framework/lib (in my case it is react) with all functionality?

**Pull request merged**
